services:
  server-api:
    build: ./server-api/
    env_file:
    - .env
    ports:
      - "5000:5000"
    depends_on:
      - otel-collector
    restart: unless-stopped

  client-api:
    build: ./client-api/
    env_file:
    - .env
    ports:
      - "5001:5001"
    depends_on:
      - server-api
      - otel-collector
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    env_file:
      - .env
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
